export const dynamic = 'force-static'

export const metadata = { title: 'Terms of Service — SEO Keyword Tracker' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-gray-300 px-4 py-12">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: July 14, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By using SEO Keyword Tracker ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. Description of Service</h2>
            <p>SEO Keyword Tracker is a web application that generates SEO keyword suggestions for restaurants, tracks keyword rankings over time, and integrates with Google Search Console and Google Analytics to display real search data.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. Data Accuracy</h2>
            <p>Keyword search volumes and difficulty scores are estimates generated by AI. Real ranking data comes directly from Google Search Console when connected. We do not guarantee the accuracy of AI-estimated data. Always verify critical SEO decisions with multiple sources.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. Google API Usage</h2>
            <p>The Service integrates with Google APIs (Search Console, Analytics, PageSpeed Insights) using OAuth 2.0. Users grant read-only access to their data. The Service complies with Google's API Services User Data Policy, including the Limited Use requirements.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the Service for illegal activities</li>
              <li>Attempt to reverse engineer or overload the Service</li>
              <li>Share your Google access tokens with unauthorized parties</li>
              <li>Use the Service to harm competitors' SEO rankings</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">6. Limitation of Liability</h2>
            <p>The Service is provided "as is" without warranties. We are not liable for any SEO decisions made based on the data provided. Google API data is subject to Google's own accuracy and availability.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">7. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">8. Contact</h2>
            <p>For questions about these Terms, contact: arjunvashishtha2004@gmail.com</p>
          </section>
        </div>
      </div>
    </div>
  )
}
