export const dynamic = 'force-static'

export const metadata = { title: 'Privacy Policy — SEO Keyword Tracker' }

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-gray-300 px-4 py-12">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-white mb-6">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: July 14, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Information We Collect</h2>
            <p>SEO Keyword Tracker collects the following information when you use our service:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Restaurant names, locations, and website URLs you search for</li>
              <li>SEO keyword data generated by AI and Google Autocomplete</li>
              <li>Google Search Console and Google Analytics data (only when you explicitly connect your Google account)</li>
              <li>Ranking history data you enter manually</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. How We Use Your Information</h2>
            <p>We use the collected information to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Generate and display SEO keyword reports</li>
              <li>Track keyword rankings over time</li>
              <li>Display real Google Search Console and Analytics data when connected</li>
              <li>Improve our keyword generation accuracy</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. Google API Data Access</h2>
            <p>When you connect your Google account, we request read-only access to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>Google Search Console</strong> — to display real search queries, impressions, clicks, and ranking positions</li>
              <li><strong>Google Analytics</strong> — to display real visitor counts, traffic sources, and page views</li>
            </ul>
            <p className="mt-2">We only read this data. We never modify, delete, or share your Google data with third parties. Access tokens are used temporarily in your browser session and are not stored on our servers.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. Data Storage</h2>
            <p>Keyword data and ranking history are stored in our database (Turso/libSQL). Your Google access tokens are NOT stored — they remain in your browser session only and expire when you close the app.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. Third-Party Services</h2>
            <p>We use the following third-party services:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong>Google APIs</strong> — Search Console, Analytics, PageSpeed Insights, Autocomplete</li>
              <li><strong>Z.AI (GLM-4.5-flash)</strong> — for AI keyword generation</li>
              <li><strong>Vercel</strong> — for hosting the application</li>
              <li><strong>Turso</strong> — for database storage</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">6. Data Deletion</h2>
            <p>You can delete any restaurant and all its associated keyword data at any time by clicking the delete button in the app. When you disconnect your Google account, we immediately discard the access token.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">7. Contact</h2>
            <p>For privacy questions or data deletion requests, contact: arjunvashishtha2004@gmail.com</p>
          </section>
        </div>
      </div>
    </div>
  )
}
